
            
            $(document).ready(function(){
             $("#all").click(function(){
                  $("#ui1").slideToggle("slow");
                  $("#ui2").slideToggle("slow");
                  $("#ui3").slideToggle("slow");
                  $("#ui4").slideToggle("slow");
                  $("#ui5").slideToggle("slow");
                  $("#ui6").slideToggle("slow");
                  $("#ui7").slideToggle("slow");
                  $("#ui8").slideToggle("slow");
                 
                 });
                $("#ide").click(function(){
                   $("#ui2").slideToggle("slow");
                   $("#ui3").slideToggle("slow");
                   $("#ui4").slideToggle("slow");
                    $("#ui1").css.style("dispaly","none");
                    $("#ui5").css.style("dispaly","none");
                    $("#ui6").css.style("dispaly","none");
                    $("#ui7").css.style("dispaly","none");
                    $("#ui8").css.style("dispaly","none");
                 });
             $("#uii").click(function(){
               $("#ui2").slideToggle("slow");
               $("#ui3").slideToggle("slow");
               $("#ui4").slideToggle("slow");
              }); 
              $("#ill").click(function(){
                 $("#ui4").slideToggle("slow");
                 $("#ui5").slideToggle("slow");
                 $("#ui6").slideToggle("slow");
                 });
             $("#brd").click(function(){
               $("#ui6").slideToggle("slow");
               $("#ui7").slideToggle("slow");
               $("#ui8").slideToggle("slow");
              }); 
               }); 